let locations = [
    {id: 1, name: "Cape Kidnappers", link: "https://www.doc.govt.nz/parks-and-recreation/places-to-go/hawkes-bay/places/cape-kidnappers-gannet-reserve/?tab-id=50578", image_location: "images/cape.jpg", description: "Cape kidnappers is a headland that sits at the end of a 8km long peninsula which protrudes into the Pacific ocean. It is a popular spot for tourists due to it being a place of importance for these birds, as it is where the gannets breed."},
    {id: 2, name: "Blowhard Bush", link: "https://www.forestandbird.org.nz/projects/blowhard-bush-reserve-hastings", image_location: "images/blowhard.jpg", description: "The 63-hectare reserve is rich in natural and social history. It is founded on a bed of Waitotarian limestone that has been repeatedly covered in pumice ash from central North Island eruptions and is covered in a distinctive red-brown soil base. The forest contains many caves, fascinating rock formations and water-cut passages.<br><br>Despite being repeatedly felled for timber, several forest giants still exist in Blowhard Bush, including one matai that is 25 metres tall and is thought to be 7-800 years old.<br><br>The various walks in the reserve take you through kanuka and beech forest and many interesting rock passages. The reserve is also home to a cave that housed a family in the 1800’s. Forest & Bird volunteers work on the reserve planting native species and eradicating introduced pests including possums, rats, mustelids, feral cats and plant pests such as broom and wilding pines. Their efforts have been rewarded with flourishing birdlife and regenerating native bush."},
    {id: 3, name: "Shine falls", link: "https://www.doc.govt.nz/parks-and-recreation/places-to-go/hawkes-bay/places/boundary-stream-area/things-to-do/heays-access-road-to-shine-falls-track/", image_location: "images/shine.jpg", description: "Hawke's Bay's most spectacular waterfall, the 58-metre Shine Falls is located on the Boundary Stream. The walk to the waterfall goes through the mixed lowland forest including kanuka, kawakawa, kowhai and titoki. <br>"},
    {id: 4, name: "Big Redwoods Trail ", link: "https://www.tematapark.co.nz/walking-trails/", image_location: "images/redwoods.jpg", description: "An outing to the stunning Te Hau Valley (Giant) Redwoods is the perfect spot for a picnic, or game of hide and seek. The loop track takes in a great lookout point over the Heretaunga Plains, the Giant Redwoods, and beautiful native bush."},
    {id: 5, name: "Rose & Shamrock", link: "https://www.roseandshamrock.co.nz", image_location: "images/r&s.jpg", description: "The Rose & Shamrock is an authentic English/Irish pub (hence the Rose & Shamrock) that proudly offers Hawke’s Bay’s largest selection of local, international, craft and time-honoured hand pulled beers and ales - located in the heart of havelock north village. <br><br> The bar and restaurant has a cosy and warm traditional vibe, and is just the place to get good quality, fresh pub food that satisfies and caters to every taste. Our team are passionate, positive, fun individuals all there to ensure guests have a fantastic experience - so please pop in with friends or family and enjoy the hospitality."},
    {id: 6, name: "Craggy Range", link: "https://craggyrange.com", image_location: "images/craggy.jpg", description: "Craggy Range is a family-owned winery established in 1998 and situated in the shadow of the spectacular Te Mata Peak <br> in the premium wine growing area of Hawke’s Bay, New Zealand. <br><br> Craggy Range produces a collection of iconic wines from multiple regions in New Zealand. Owner Terry Peabody and his family pursued the single vineyard approach to winemaking, planting on green fields and bare land ensuring a focus on quality from the very beginning."},
    {id: 7, name: "Off the Track", link: "https://offthetrack.co.nz", image_location: "images/track-alt.jpg", description: "Off The Track is the perfect retreat for a casual meal, a drink with friends or a delicious coffee. They offer a wide range of dishes to suit all tastes and budgets."},
    {id: 8, name: "Brave Brewery", link: "https://www.bravebrewing.co.nz", image_location: "images/brave.jpg", description: "Established in 2014, Brave is a friendly, neighbourhood brewery situated in the heart of Hastings, Hawke's Bay. What began as a hobby has blossomed into an award-winning brewery, cherished by locals and visitors alike."},
    {id: 9, name: "GoBay Bus Service", link: "https://www.gobay.co.nz", image_location: "images/gobay.jpg", description: "The Hawke's Bay public bus transport system run by the council."},
    {id: 10, name: "Pegasus Car Hire", link: "https://www.rentalcars.co.nz", image_location: "images/pegasus.jpg", description: "A nationwide car rental operation that is not owned by an overseas corporate. A unique feature of the Pegasus Rental Car company is that all of our rental branches are franchised to owner/operators who really know their business and local area."},
    {id: 11, name: "RaD Car Hire", link: "https://www.radcarhire.co.nz", image_location: "images/RaD.jpg", description: "RaD Car Hire has been servicing the rental vehicle needs of everyday people from New Zealand and overseas. Starting as a single branch in Tauranga in 1987, RaD Car Hire now proudly offers one of the largest rental vehicle networks in New Zealand. RaD Car Hire is a franchised network with each branch being owned and operated by locals from that area. This ensures that wherever you go the local RaD branch will have its finger on the pulse of local activities and hold a wealth of local knowledge."},
    {id: 12, name: "Apex Car Hire", link: "https://www.apexrentals.co.nz", image_location: "images/apex.png", description: "Apex offers a wide selection of rental cars to suit different travel needs. Small hatchback cars are economical and ideal for around town driving or short day trips, with 1-3 passengers fitting comfortably. They also have larger hatchbacks and wagons, which provide extra space and power, that comfortably fit four passengers."},
    {id: 13, name: "Porters Hotel", link: "https://www.portershotel.co.nz", image_location: "images/porters.jpg", description: "The 4.5-star boutique hotel is owned by the families of two prominent Hawke’s Bay businessmen – property developer David Mackersey and Lowe Corporate managing director Andy Lowe. The $25 million development included the Hotel, shopping precinct, commercial office space, restaurant and wine lounge through Lowmac Properties Ltd. <br><br> The name of the Hotel is based on its placement on the corner of Porter Drive and the role of a porter is synonymous with quality luxury accommodation. Porter Drive was named after Daniel G Porter, a former town planner for the Havelock North Borough Council."},
    {id: 14, name: "The DOME", link: "https://www.thedome.co.nz", image_location: "images/dome.jpg", description: "Boutique Waterfront Art Deco accommodation in the heart of Napier. The Dome epitomises Art Deco chic, offering waterfront studio and apartment accommodation for a variety of budgets, alongside state-of the-art business facilities for private functions, conferences, seminars and presentations."},
    {id: 15, name: "Scenic Hotel Te Pania", link: "https://www.scenichotelgroup.co.nz/napier/scenic-hotel-te-pania/", image_location: "images/tepania.jpg", description: "Scenic Hotel Te Pania presents the best of the Bay with genuine Kiwi hospitality in contemporary and superior surroundings amidst a spectacular city setting. Boasting design awards for its style and offering an unmatched level of service to leisure travellers and conference guests. <br><br> Perfectly appointed rooms allow visitors to take in the views of the Hawke’s Bay and beyond and make accessing the waterfront and city attractions a breeze. Four-legged family members can enjoy waterfront “walkies” from the hotel’s ground floor dog-friendly accommodation."},
    {id: 16, name: "Art Deco Masonic Hotel", link: "https://masonic.co.nz", image_location: "images/deco.jpg", description: "Napier’s best located Boutique Hotel, on the waterfront with panoramic views of the Pacific Ocean – Masonic Hotel is an Art Deco jewel offering unique, characterful Napier accommodation options."},
    {id: 17, name: "Ocean Spa", link: "https://www.oceanspanapier.co.nz/about-us/", image_location: "images/spa.jpg", description: "Experience relaxation and revitalization at Ocean Spa, Napier's premier heated pool and fitness complex. Our open-air, heated pools and spas, as well as fully equipped gym, offer panoramic ocean views, making the perfect environment to work out and wind down.  Complete your visit with a stop at The Bach Café for superb coffee and delicious food."},
    {id: 18, name: "Arataki Honey Visitor Centre", link: "https://www.aratakihoney.co.nz/pages/visitor-centre", image_location: "images/honey.jpg", description: "Be a bee, learn about honey making, dress up as a beekeeper and snap a 3D pic. See our buzzing bees up close and taste their delicious honey! Whether visiting as an individual, a family or as part of a group, there's plenty to explore and lots to do."},
    {id: 19, name: "Par2 Minigolf", link: "https://www.par2golf.co.nz", image_location: "images/minigolf.jpg", description: "Bring your kids, bring your friends, bring your workmates! Adjacent to Napier's isite Visitor Centre on Marine Parade, Par2 MiniGolf has two 18-hole putting courses perfect for any occasion. Enjoy some friendly competition by the sea and choose either our Deco Drive or Pacific Pro-Am course. One is curvy, sloped and a little bit tricky. The other is just plain wacky with its angles, not to mention the water hazards!"},
    {id: 20, name: "Keirunga Park Railway", link: "https://www.keirungaparkrailway.org.nz", image_location: "images/railway.jpg", description: "Keirunga Park Railway, a popular 846 metre long miniature railway operated by Keirunga Park Railway Incorporated. The track winds its way around Keirunga Gardens, through tunnels, over viaducts and around scenic rock faces. Keirunga is rated in the top 5 best miniature railway tracks in New Zealand. <br><br> We regularly run on the 1st and 3rd Sunday of each month 11am to 4pm (Weather permitting). Please check our Facebook for operational announcements"}
]

let votes =[
    {id: 1, like: 1345, dislike: 10},
    {id: 2, like: 5432, dislike: 11},
    {id: 3, like: 7895, dislike: 15},
    {id: 4, like: 9287, dislike: 3},
    {id: 5, like: 9978, dislike: 2},
    {id: 6, like: 19002, dislike: 0},
    {id: 7, like: 2020, dislike: 16},
    {id: 8, like: 3241, dislike: 12},
    {id: 9, like: 2029, dislike: 10},
    {id: 10, like: 9109, dislike: 18},
    {id: 11, like: 10982, dislike: 23},
    {id: 12, like: 7860, dislike: 12},
    {id: 13, like: 8965, dislike: 21},
    {id: 14, like: 4445, dislike: 8},
    {id: 15, like: 1563, dislike: 4},
    {id: 16, like: 8973, dislike: 1},
    {id: 17, like: 19002, dislike: 0},
    {id: 18, like: 2020, dislike: 16},
    {id: 19, like: 3241, dislike: 12},
    {id: 20, like: 2029, dislike: 10}
];

//Normally data is stored in DB, when app sends a request to DB, it return this array of data
//Link: https://www.imdb.com/chart/top/
let comments =[ {id: 1, comments: [{user: "John", comment:"Good place!"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 2, comments: [{user: "Graham", comment:"Great place!"}, {user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent place"}]},
    {id: 3, comments: [{user: "John", comment:"Good Movie"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 4, comments: [{user: "Graham", comment:"Great place"}]},
    {id: 5, comments: [{user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 6, comments: [{user: "Kim", comment:"Excellent place"}]},
    {id: 7, comments: [ {user: "Ian", comment:"Must visit!"},{user: "Daniel", comment:"Recommended"}]},
    {id: 8, comments: [{user: "Noor", comment:"Very interesting"}]},
    {id: 9, comments: [{user: "John", comment:"Good place"}]},
    {id: 10, comments: [{user: "Noor", comment:"Great place, recommended"},{user: "Kim", comment:"Excellent plce"}]},
    {id: 11, comments: [{user: "John", comment:"Good place"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 12, comments: [{user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent place"}]},
    {id: 13, comments: [{user: "John", comment:"Good place"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 14, comments: [ {user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent place"}, {user: "Graham", comment:"Great place"}]},
    {id: 15, comments: [{user: "John", comment:"Good place"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 16, comments: [{user: "Kim", comment:"Excellent place"}, {user: "Graham", comment:"Great place"}, {user: "Noor", comment:"Very interesting"}]},
    {id: 17, comments: [{user: "John", comment:"Good Movie"}, {user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 18, comments: [{user: "Graham", comment:"Great place"}]},
    {id: 19, comments: [{user: "Ian", comment:"Not bad"},{user: "Daniel", comment:"Recommended"}]},
    {id: 20, comments: [{user: "Graham", comment:"Great place!"}, {user: "Noor", comment:"Very interesting"},{user: "Kim", comment:"Excellent place"}]},
];     